### ISSUE TITLE
Minor issue: window size

### ISSUE THREAD

**Issue by marcoaqil** [VU-Cog-Sci/exptools2#9]
It appears the size of the window obtained from session.win is not the same size set through the parameter file. Looks like a psychopy issue, or maybe only my system.

**Comment by lukassnoek** [comment]
My bad, this was due to a wrong initialization of the `Session` objects in the examples. I added an extra argument, `output_dir`, to the `Session` class, but the examples assumed that the second argument was the `settings_file`. As such, the settings-file was never used (all other settings were actually also not used, but you probably didn't notice this because exptools2 falls back on a set of sensible defaults). 

I've modified the examples/demos, which should now work properly. If not, let me know.
